PUT https://progresspulseapplication.onrender.com/api/plans/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OGQyNWY5MjQyYjViYTQyNGI3MWQzNjEiLCJybHYiOjEwLCJpYXQiOjE3NTg2NjE5NzksImV4cCI6MTc1ODY2Mjg3OX0.uijVJ97iAWBFNMK9GP7tTltTrgHogYWTUbohHGMubs4

{
  "days": [
    { "exercises": [ { "exerciseId": "66f130bd3d9b4c7d5a9a7e13", "sets": 3 } ] },
    { "exercises": [ { "exerciseId": "66f130bd3d9b4c7d5a9a7e52", "sets": 4 } ] }
  ],
  "locked": true
}