GET https://progresspulseapplication.onrender.com/api/exercises?muscle=Back&limit=10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OGQyNWY5MjQyYjViYTQyNGI3MWQzNjEiLCJybHYiOjEwLCJpYXQiOjE3NTg2NjkxNzgsImV4cCI6MTc1ODY3MDA3OH0.Drb3IT55JBe6CrQIPDJRP22_NNvGJ1XvwXvic9XFGuk

###
GET https://progresspulseapplication.onrender.com/api/exercises?query=lat
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OGQyNWY5MjQyYjViYTQyNGI3MWQzNjEiLCJybHYiOjEwLCJpYXQiOjE3NTg2NzA2ODgsImV4cCI6MTc1ODY3MTU4OH0._m3lUmHkiGhaw11943zlItzwIMirFfd3VDxTsJvb3Hg



###

POST https://progresspulseapplication.onrender.com/api/exercises
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OGQzMzIxNDMxMGFhYTRhM2EwMTcxYjUiLCJybHYiOjEwLCJpYXQiOjE3NTg2NzM3MTEsImV4cCI6MTc1ODY3NDYxMX0.sPtPtaYTgamXiP1V1FSbdd6l46JipVB6HgqUHkBI6Ew

{
  "name": "Cable Crossover",
  "muscle": "Chest",
  "type": "Isolation",
  "equipment": "Cable"
}



### מחיקה עם אדמין
DELETE https://progresspulseapplication.onrender.com/api/exercises/68d323efcfbe22f2c15df947
Authorization: Bearer <ADMIN_ACCESS_TOKEN